services:
  - type: web
    name: navi-iq-frontend
    buildCommand: ./render-build.sh
    staticPublishPath: ./dist
    # Improved SPA routing configuration
    routes:
      - type: rewrite
        source: /**
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: X-Frame-Options
        value: DENY
